SELECT PRODUCT_ID, PRODUCT_NAME, (PRICE * SUB.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT
JOIN (
    SELECT PRODUCT_ID AS ID, PRODUCE_DATE AS DATE, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER 
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) SUB 
ON SUB.ID = PRODUCT_ID 
WHERE YEAR(SUB.DATE) = 2022 
AND MONTH(SUB.DATE) = 5
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
