SELECT A.AUTHOR_ID
    , B.AUTHOR_NAME
    , A.CATEGORY
    , SUM(C.SALES * PRICE) AS TOTAL_SALES
    # , (SUM(C.SALES) * SUM(A.PRICE)) AS TOTAL_SALES 오답 
FROM BOOK AS A
INNER JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, CATEGORY
# GROUP BY A.AUTHOR_ID, A. BOOK_ID 오답 
ORDER BY A.AUTHOR_ID, CATEGORY DESC
